/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KNN */

#ifndef _Included_KNN
#define _Included_KNN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KNN
 * Method:    KNN_search
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_KNN_KNN_1search
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
